// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, unused_element

class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? iosBundleId;

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.storageBucket,
    this.iosBundleId,
  });
}

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJG-KGFPjypb74krEKUy37kLUaFuqYfAM',
    appId: '1:918419916002:web:8d40d9bf19ea8f12cc8abb',
    messagingSenderId: '918419916002',
    projectId: 'intellideskai-83763',
    authDomain: 'intellideskai-83763.firebaseapp.com',
    storageBucket: 'intellideskai-83763.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVg2cG7H14Q9LDgZ_kPwflNWrWbooj79c',
    appId: '1:918419916002:android:23b4f09e4e408617cc8abb',
    messagingSenderId: '918419916002',
    projectId: 'intellideskai-83763',
    storageBucket: 'intellideskai-83763.firebasestorage.app',
  );
}

